name: game
description: "Legend Festival: Cross Event Game"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  google_mobile_ads: ^5.2.0
  flutter:
    sdk: flutter
  flame: ^1.13.0
  flame_audio: ^2.1.0
  get_it: ^9.2.0
  provider: ^6.1.1
  equatable: ^2.0.5
  mg_common_game:
    path: ../libs/mg_common_game
  cupertino_icons: ^1.0.8

dev_dependencies:
  google_mobile_ads: ^5.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
